### ISSUE TITLE
arguments are located on different GPUs

### ISSUE THREAD

**Issue by fuyw** [BangLiu/QANet-PyTorch#3]
Hi BangLiu, thanks for this awesome code :)

I want to run QANet with 4 gpus and I change some related settings as:

```
parser.add_argument('--with_cuda', default=True)
parser.add_argument('--multi_gpu', default=True)

model = nn.DataParallel(model, device_ids=[0, 1, 2, 3])
```
I am using `torch 0.4.0` and `cuda 9.0`.  And I meet with a runtime error `arguments are located on different GPUs` as follow:

```
Traceback (most recent call last):
  File "QANet_main.py", line 633, in <module>
    p1, p2 = trainer.model(context_wids, context_cids, question_wids, question_cids)
  File "/home/fuyuwei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fuyuwei/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/fuyuwei/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/fuyuwei/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
  File "/home/fuyuwei/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 41, in _worker
    output = module(*input, **kwargs)
  File "/home/fuyuwei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fuyuwei/CODE/_QANet/model/QANet_andy.py", line 353, in forward
    Ce = self.emb_enc(C, maskC, 1, 1)
  File "/home/fuyuwei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fuyuwei/CODE/_QANet/model/QANet_andy.py", line 224, in forward
    out = PosEncoder(x)
  File "/home/fuyuwei/CODE/_QANet/model/QANet_andy.py", line 55, in PosEncoder
    return (x + signal.to(device)).transpose(1, 2)
RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:233
```
It seems that the error is due to in `PosEncoder()` where the input `x` and `signal.to(device)` is on different gpus.

Could you please provide some clue to solve this problem?  Many thanks.

**Comment by fuyw** [comment]
I use `signal.to(x.get_device())` instead for `PosEncoder()` in `QANet_andy.py`:

```
def PosEncoder(x, min_timescale=1.0, max_timescale=1.0e4):
    x = x.transpose(1, 2)
    length = x.size()[1]
    channels = x.size()[2]
    signal = get_timing_signal(length, channels, min_timescale, max_timescale)
    return (x + signal.to(x.get_device())).transpose(1, 2)
```
And I can run the QANet with 4 gpus with no errors.

I'm new to PyTorch, and not sure if I am right?

**Comment by BangLiu** [comment]
Hi @fuyw , actually I never tried multi-GPU setting, as I only have one GPU at present. I will test it when I have access to a multi gpu training platform. How about your result using 4 GPUs? If your performance is similar, then I think you are right.

**Comment by rsanjaykamath** [comment]
Hi @BangLiu, Which GPU did you use to train these models? I'm getting a memory error when I try it on GTX 1080Ti.

**Comment by fuyw** [comment]
@rsanjaykamath maybe you should decrease the batch size

**Comment by rsanjaykamath** [comment]
I tried with batchsize 16. Still the same error. 

Built 10482 / 10570 instances of features in total
Saving word embedding...
Saving char embedding...
Saving word dictionary...
Saving char dictionary...
Saving train examples...
Saving dev examples...
Saving train meta...
Saving dev meta...
Saving train eval...
Saving dev eval...
Trainable parameters: 1295689
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "QANet_main.py", line 377, in <module>
    main(parser.parse_args())
  File "QANet_main.py", line 372, in main
    trainer.train()
  File "/people/sanjay/QANet-PyTorch/trainer/QANet_trainer.py", line 81, in train
    result = self._train_epoch(epoch)
  File "/people/sanjay/QANet-PyTorch/trainer/QANet_trainer.py", line 143, in _train_epoch
    question_cids)
  File "/people/sanjay/anaconda2/envs/pytorch4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/people/sanjay/QANet-PyTorch/model/QANet_andy.py", line 365, in forward
    M0 = blk(M0, maskC, i*(2+2)+1, 7)
  File "/people/sanjay/anaconda2/envs/pytorch4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/people/sanjay/QANet-PyTorch/model/QANet_andy.py", line 235, in forward
    out = self.self_att(out, mask)
  File "/people/sanjay/anaconda2/envs/pytorch4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/people/sanjay/QANet-PyTorch/model/QANet_andy.py", line 125, in forward
    x = self.dot_product_attention(Q, K, V, mask = mask)
  File "/people/sanjay/QANet-PyTorch/model/QANet_andy.py", line 149, in dot_product_attention
    weights = F.dropout(weights, p=self.dropout, training=self.training)
  File "/people/sanjay/anaconda2/envs/pytorch4/lib/python3.6/site-packages/torch/nn/functional.py", line 552, in dropout
    return _functions.dropout.Dropout.apply(input, p, training, inplace)
  File "/people/sanjay/anaconda2/envs/pytorch4/lib/python3.6/site-packages/torch/nn/_functions/dropout.py", line 40, in forward
    ctx.noise.bernoulli_(1 - ctx.p).div_(1 - ctx.p)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCStorage.cu:58

**Comment by fuyw** [comment]
I think you can use `nvidia-smi` to check your gpu usage, in case some other program is using the gpu.

and try batch_size = 4 or 8  to see if it works.

**Comment by rsanjaykamath** [comment]
Ok, it works for me at batch_size = 8 
Thanks for the code. 

Do you have a checklist of things which differ from the implementation based on the paper? 
I'm asking because of the difference in performance when we compare to the original paper without translations. 

Thanks again.
